import { SURFACE_KEYS } from "./enums.js";
import { SURFACE_ACTIONS } from "./surface-actions.js";
import { glyphColorSpecs } from "./glyph-presets.js";
import {
  createConfigDialogRow,
  createGridPlainCard,
  createGridSingleRowCard,
  createSurfaceTabsTemplate,
} from "./settings-templates.js";

export const SETTINGS_NODE_KINDS = Object.freeze({
  CARD: "card",
  DROPDOWN: "dropdown",
  TOGGLE: "toggle",
  STEPPER: "stepper",
  DIALOG: "dialog",
  EXPANDER: "expander",
  SURFACE_TABS: "surfaceTabs",
});

function withSurfaceAction(node, action) {
  if (!action) {
    return {
      ...node,
      surface: node.surface ?? null,
      section: node.section ?? null,
      scope: node.scope ?? null,
      renderTarget: node.renderTarget ?? null,
      persistTarget: node.persistTarget ?? null,
    };
  }

  return {
    ...node,
    surface: action.surface,
    section: action.section,
    scope: action.scope,
    actionKey: action.key,
    renderTarget: action.renderTarget,
    persistTarget: action.persistTarget,
  };
}

function createGlyphHighlightChildren() {
  return glyphColorSpecs.map((spec) =>
    withSurfaceAction(
      {
        id: `glyphColor:${spec.key}`,
        kind: SETTINGS_NODE_KINDS.DROPDOWN,
        variant: "glyphColor",
        labelKey: "symbolHighlight",
        label: spec.label,
        valueSource: `glyphColor:${spec.key}`,
        optionsSource: "glyphColorOptions",
        glyphKey: spec.key,
        previewToken: spec.token,
      },
      SURFACE_ACTIONS.EDITOR_GLYPH_COLOR,
    ),
  );
}

const themeTabChildren = [
  createGridPlainCard("themeFontCard", [
      withSurfaceAction(
        {
          id: "interfaceFont",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "interfaceFont",
          label: "Font",
          titleId: "interfaceFontTitle",
          valueSource: "interfaceFont",
          buttonId: "interfaceFontButton",
          optionsId: "interfaceFontOptions",
          optionsSource: "interfaceFonts",
        },
        SURFACE_ACTIONS.INTERFACE_FONT,
      ),
      withSurfaceAction(
        {
          id: "interfaceSize",
          kind: SETTINGS_NODE_KINDS.STEPPER,
          labelKey: "interfaceSize",
          label: "Font Size",
          titleId: "interfaceSizeTitle",
          valueSource: "interfaceSize",
          controlId: "interfaceSizeControl",
          decreaseId: "interfaceSizeDecrease",
          increaseId: "interfaceSizeIncrease",
          valueId: "interfaceSizeValue",
        },
        SURFACE_ACTIONS.INTERFACE_SIZE,
      ),
    ],
  ),
  createGridPlainCard("themeColorCard", [
      withSurfaceAction(
        {
          id: "themePalette",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "themePalette",
          label: "Palette",
          titleId: "themePaletteTitle",
          valueSource: "themePalette",
          buttonId: "themePaletteButton",
          optionsId: "themePaletteOptions",
          optionsSource: "themePalettes",
        },
        SURFACE_ACTIONS.THEME_PALETTE,
      ),
      withSurfaceAction(
        {
          id: "themeText",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "themeText",
          label: "Text",
          titleId: "themeTextTitle",
          valueSource: "themeText",
          buttonId: "themeTextButton",
          optionsId: "themeTextOptions",
          optionsSource: "themeText",
        },
        SURFACE_ACTIONS.THEME_TEXT,
      ),
      withSurfaceAction(
        {
          id: "themeColor",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "themeColor",
          label: "Icon",
          titleId: "themeColorTitle",
          valueSource: "themeColor",
          buttonId: "themeColorButton",
          optionsId: "themeColorOptions",
          optionsSource: "themeColors",
        },
        SURFACE_ACTIONS.THEME_COLOR,
      ),
      withSurfaceAction(
        {
          id: "themeLines",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "lines",
          label: "Lines",
          titleId: "themeLineTitle",
          valueSource: "themeLines",
          buttonId: "themeLineButton",
          optionsId: "themeLineOptions",
          optionsSource: "themeLines",
        },
        SURFACE_ACTIONS.THEME_LINES,
      ),
      withSurfaceAction(
        {
          id: "themeBackground",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "background",
          label: "Background",
          titleId: "themeBackgroundTitle",
          valueSource: "themeBackground",
          buttonId: "themeBackgroundButton",
          optionsId: "themeBackgroundOptions",
          optionsSource: "themeBackgrounds",
        },
        SURFACE_ACTIONS.THEME_BACKGROUND,
      ),
    ],
  ),
  createGridSingleRowCard(
    "themeConfigCard",
    createConfigDialogRow({
      id: "themeConfig",
      titleId: "themeConfigTitle",
      valueSource: "themeConfig",
      persistTarget: "themeConfig",
      importButtonId: "importThemeConfigButton",
      editButtonId: "editThemeConfigButton",
    }),
  ),
];

const editorTabChildren = [
  createGridSingleRowCard(
    "editorGlyphCompositionCard",
      withSurfaceAction(
        {
          id: "glyphComposition",
          kind: SETTINGS_NODE_KINDS.TOGGLE,
          variant: "iconSwitch",
          labelKey: "glyphComposition",
          label: "Glyph Composition",
          titleId: "glyphCompositionTitle",
          valueSource: "glyphComposition",
          buttonId: "toggleGlyphs",
          actionKey: "glyphComposition",
          renderTarget: SURFACE_ACTIONS.EDITOR_GLYPH_COLOR.renderTarget,
          persistTarget: SURFACE_ACTIONS.EDITOR_GLYPH_COLOR.persistTarget,
        },
        null,
      ),
  ),
  createGridSingleRowCard(
    "editorTabSizeCard",
      withSurfaceAction(
        {
          id: "tabSize",
          kind: SETTINGS_NODE_KINDS.TOGGLE,
          variant: "segment",
          labelKey: "tabSize",
          label: "Tab Size",
          titleId: "tabSizeTitle",
          valueSource: "tabSize",
          containerId: "indentControl",
          actionKey: "tabSize",
          renderTarget: SURFACE_ACTIONS.EDITOR_FONT.renderTarget,
          persistTarget: SURFACE_ACTIONS.EDITOR_FONT.persistTarget,
          optionsSource: "tabSizes",
        },
        null,
      ),
  ),
  createGridPlainCard("editorFontCard", [
      withSurfaceAction(
        {
          id: "editorFont",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "editorFont",
          label: "Font",
          titleId: "editorFontTitle",
          valueSource: "editorFont",
          buttonId: "editorFontButton",
          optionsId: "editorFontOptions",
          optionsSource: "editorFonts",
        },
        SURFACE_ACTIONS.EDITOR_FONT,
      ),
      withSurfaceAction(
        {
          id: "editorFontSize",
          kind: SETTINGS_NODE_KINDS.STEPPER,
          labelKey: "editorFontSize",
          label: "Font Size",
          titleId: "editorFontSizeTitle",
          valueSource: "editorFontSize",
          controlId: "editorFontSizeControl",
          decreaseId: "editorFontSizeDecrease",
          increaseId: "editorFontSizeIncrease",
          valueId: "editorFontSizeValue",
        },
        SURFACE_ACTIONS.EDITOR_FONT_SIZE,
      ),
    ],
  ),
  createGridPlainCard("editorColorCard", [
      withSurfaceAction(
        {
          id: "editorPalette",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "palette",
          label: "Palette",
          titleId: "editorPaletteTitle",
          valueSource: "editorPalette",
          buttonId: "highlightPaletteButton",
          optionsId: "highlightPaletteOptions",
          optionsSource: "editorPalettes",
        },
        SURFACE_ACTIONS.EDITOR_PALETTE,
      ),
      withSurfaceAction(
        {
          id: "editorBackground",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "editorBackground",
          label: "Background",
          titleId: "editorBackgroundTitle",
          valueSource: "editorBackground",
          buttonId: "editorBackgroundButton",
          optionsId: "editorBackgroundOptions",
          optionsSource: "editorBackgrounds",
        },
        SURFACE_ACTIONS.EDITOR_BACKGROUND,
      ),
      withSurfaceAction(
        {
          id: "editorTextColor",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "textColor",
          label: "Text",
          titleId: "textColorTitle",
          valueSource: "editorTextColor",
          buttonId: "textColorButton",
          optionsId: "textColorOptions",
          optionsSource: "editorTextColors",
        },
        SURFACE_ACTIONS.EDITOR_TEXT_COLOR,
      ),
      withSurfaceAction(
        {
          id: "editorTextHighlight",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "textHighlight",
          label: "Keyword",
          titleId: "textHighlightTitle",
          valueSource: "editorTextHighlight",
          buttonId: "textHighlightButton",
          optionsId: "textHighlightOptions",
          optionsSource: "editorTextHighlights",
        },
        SURFACE_ACTIONS.EDITOR_TEXT_HIGHLIGHT,
      ),
      {
        id: "symbolHighlightDisclosure",
        kind: SETTINGS_NODE_KINDS.EXPANDER,
        nested: true,
        surface: SURFACE_KEYS.EDITOR,
        section: SURFACE_ACTIONS.EDITOR_GLYPH_COLOR.section,
        scope: SURFACE_ACTIONS.EDITOR_GLYPH_COLOR.scope,
        labelKey: "symbolHighlight",
        label: "Symbols",
        titleId: "symbolColorsTitle",
        renderTarget: SURFACE_ACTIONS.EDITOR_GLYPH_COLOR.renderTarget,
        persistTarget: SURFACE_ACTIONS.EDITOR_GLYPH_COLOR.persistTarget,
        listId: "glyphColorList",
        children: createGlyphHighlightChildren(),
      },
    ],
  ),
  createGridPlainCard("editorSurfaceCard", [
      withSurfaceAction(
        {
          id: "editorBlockStyle",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "block",
          label: "Block",
          titleId: "blockTitle",
          valueSource: "editorBlockStyle",
          buttonId: "blockSurfaceButton",
          optionsId: "blockSurfaceOptions",
          optionsSource: "blockStyles",
        },
        SURFACE_ACTIONS.EDITOR_BLOCK_STYLE,
      ),
      withSurfaceAction(
        {
          id: "editorLineStyle",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "line",
          label: "Line",
          titleId: "lineTitle",
          valueSource: "editorLineStyle",
          buttonId: "lineHighlightButton",
          optionsId: "lineHighlightOptions",
          optionsSource: "lineStyles",
        },
        SURFACE_ACTIONS.EDITOR_LINE_STYLE,
      ),
      withSurfaceAction(
        {
          id: "editorSelectionStyle",
          kind: SETTINGS_NODE_KINDS.DROPDOWN,
          labelKey: "selection",
          label: "Selection",
          titleId: "selectionTitle",
          valueSource: "editorSelectionStyle",
          buttonId: "selectionHighlightButton",
          optionsId: "selectionHighlightOptions",
          optionsSource: "selectionStyles",
        },
        SURFACE_ACTIONS.EDITOR_SELECTION_STYLE,
      ),
    ],
  ),
  createGridSingleRowCard(
    "editorConfigCard",
    createConfigDialogRow({
      id: "editorConfig",
      titleId: "editorConfigTitle",
      valueSource: "editorConfig",
      persistTarget: "editorConfig",
      importButtonId: "importEditorConfigButton",
      editButtonId: "editEditorConfigButton",
    }),
  ),
];

export const settingsCardsSchema = [
  withSurfaceAction(
    {
      id: "language",
      kind: SETTINGS_NODE_KINDS.DROPDOWN,
      labelKey: "language",
      label: "Language",
      titleId: "languageTitle",
      valueSource: "language",
      buttonId: "languageModeButton",
      optionsId: "languageModeOptions",
      optionsSource: "languageOptions",
      compact: true,
      actionKey: "language",
      renderTarget: "settingsState",
      persistTarget: "language",
    },
    null,
  ),
  withSurfaceAction(
    {
      id: "style",
      kind: SETTINGS_NODE_KINDS.DROPDOWN,
      labelKey: "style",
      label: "Style",
      titleId: "styleTitle",
      valueSource: "style",
      buttonId: "styleButton",
      optionsId: "styleOptions",
      optionsSource: "uiStyles",
      actionKey: "style",
      renderTarget: "settingsState",
      persistTarget: "uiStyle",
    },
    null,
  ),
  withSurfaceAction(
    {
      id: "autoSave",
      kind: SETTINGS_NODE_KINDS.DROPDOWN,
      variant: "stacked",
      labelKey: "autoSave",
      label: "Auto Save",
      titleId: "autoSaveTitle",
      valueSource: "autoSave",
      buttonId: "autoSaveModeButton",
      optionsId: "autoSaveModeOptions",
      optionsSource: "autoSaveModes",
      actionKey: "autoSaveMode",
      renderTarget: "settingsState",
      persistTarget: "autoSave",
      auxiliary: {
        kind: "delayInput",
        fieldId: "autoSaveDelayField",
        labelId: "autoSaveDelayLabel",
        inputId: "autoSaveDelayInput",
        labelKey: "delay",
      },
    },
    null,
  ),
  createSurfaceTabsTemplate({
    id: "linkedSurfaceModeCard",
    labelKey: "surfaceModeBridge",
    label: "Surface Mode",
    titleId: "linkedSurfaceModeCardTitle",
    modeTitleId: "linkedSurfaceModeTitle",
    modeLabelKey: "mode",
    modeLabel: "Mode",
    themeTabId: "linkedSurfaceThemeTab",
    editorTabId: "linkedSurfaceEditorTab",
    linkButtonId: "linkedEditorModeLinkButton",
    toggleContainerId: "linkedSurfaceModeToggle",
    darkId: "linkedSurfaceModeDark",
    lightId: "linkedSurfaceModeLight",
    themePanelId: "linkedSurfaceThemePanel",
    editorPanelId: "linkedSurfaceEditorPanel",
    themeChildren: themeTabChildren,
    editorChildren: editorTabChildren,
    tabs: [
      {
        key: SURFACE_KEYS.THEME,
        labelKey: "theme",
        label: "Theme",
      },
      {
        key: SURFACE_KEYS.EDITOR,
        labelKey: "editor",
        label: "Editor",
      },
    ],
  }),
];
