import { SURFACE_KEYS } from "./enums.js";

export const SURFACE_ACTION_SCOPES = Object.freeze({
  SURFACE: "surface",
  SECTION: "section",
  LEAF: "leaf",
});

export const SURFACE_SECTION_KEYS = Object.freeze({
  MODE: "mode",
  PALETTE: "palette",
  FONT: "font",
  COLOR: "color",
  BLOCK: "block",
  LINE: "line",
  SELECTION: "selection",
  GLYPH: "glyph",
});

export const SURFACE_RENDER_TARGETS = Object.freeze({
  THEME_SURFACE: "themeSurface",
  THEME_FONT: "themeFont",
  THEME_COLOR: "themeColor",
  EDITOR_SURFACE: "editorSurface",
  EDITOR_FONT: "editorFont",
  EDITOR_COLOR: "editorColor",
  EDITOR_BLOCK: "editorBlock",
  EDITOR_LINE: "editorLine",
  EDITOR_SELECTION: "editorSelection",
  EDITOR_GLYPH: "editorGlyph",
});

export const SURFACE_PERSIST_TARGETS = Object.freeze({
  THEME: "theme",
  EDITOR: "editor",
  EDITOR_PREFERENCES: "editorPreferences",
  EDITOR_GLYPHS: "editorGlyphs",
});

export const SURFACE_ACTIONS = Object.freeze({
  THEME_MODE: {
    key: "themeMode",
    surface: SURFACE_KEYS.THEME,
    scope: SURFACE_ACTION_SCOPES.SURFACE,
    section: SURFACE_SECTION_KEYS.MODE,
    renderTarget: SURFACE_RENDER_TARGETS.THEME_SURFACE,
    persistTarget: SURFACE_PERSIST_TARGETS.THEME,
  },
  THEME_PALETTE: {
    key: "themePalette",
    surface: SURFACE_KEYS.THEME,
    scope: SURFACE_ACTION_SCOPES.SURFACE,
    section: SURFACE_SECTION_KEYS.PALETTE,
    renderTarget: SURFACE_RENDER_TARGETS.THEME_SURFACE,
    persistTarget: SURFACE_PERSIST_TARGETS.THEME,
  },
  THEME_TEXT: {
    key: "themeText",
    surface: SURFACE_KEYS.THEME,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.COLOR,
    renderTarget: SURFACE_RENDER_TARGETS.THEME_COLOR,
    persistTarget: SURFACE_PERSIST_TARGETS.THEME,
  },
  THEME_COLOR: {
    key: "themeColor",
    surface: SURFACE_KEYS.THEME,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.COLOR,
    renderTarget: SURFACE_RENDER_TARGETS.THEME_COLOR,
    persistTarget: SURFACE_PERSIST_TARGETS.THEME,
  },
  THEME_BACKGROUND: {
    key: "themeBackground",
    surface: SURFACE_KEYS.THEME,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.COLOR,
    renderTarget: SURFACE_RENDER_TARGETS.THEME_COLOR,
    persistTarget: SURFACE_PERSIST_TARGETS.THEME,
  },
  THEME_LINES: {
    key: "themeLines",
    surface: SURFACE_KEYS.THEME,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.COLOR,
    renderTarget: SURFACE_RENDER_TARGETS.THEME_COLOR,
    persistTarget: SURFACE_PERSIST_TARGETS.THEME,
  },
  INTERFACE_FONT: {
    key: "interfaceFont",
    surface: SURFACE_KEYS.THEME,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.FONT,
    renderTarget: SURFACE_RENDER_TARGETS.THEME_FONT,
    persistTarget: SURFACE_PERSIST_TARGETS.THEME,
  },
  INTERFACE_SIZE: {
    key: "interfaceSize",
    surface: SURFACE_KEYS.THEME,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.FONT,
    renderTarget: SURFACE_RENDER_TARGETS.THEME_FONT,
    persistTarget: SURFACE_PERSIST_TARGETS.THEME,
  },
  EDITOR_MODE: {
    key: "editorMode",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.SURFACE,
    section: SURFACE_SECTION_KEYS.MODE,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_SURFACE,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR,
  },
  EDITOR_PALETTE: {
    key: "editorPalette",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.SURFACE,
    section: SURFACE_SECTION_KEYS.PALETTE,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_SURFACE,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR,
  },
  EDITOR_FONT: {
    key: "editorFont",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.FONT,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_FONT,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR_PREFERENCES,
  },
  EDITOR_FONT_SIZE: {
    key: "editorFontSize",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.FONT,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_FONT,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR_PREFERENCES,
  },
  EDITOR_BACKGROUND: {
    key: "editorBackground",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.COLOR,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_COLOR,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR,
  },
  EDITOR_TEXT_COLOR: {
    key: "editorTextColor",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.COLOR,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_COLOR,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR,
  },
  EDITOR_TEXT_HIGHLIGHT: {
    key: "editorTextHighlight",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.SECTION,
    section: SURFACE_SECTION_KEYS.COLOR,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_COLOR,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR,
  },
  EDITOR_BLOCK_STYLE: {
    key: "editorBlockStyle",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.LEAF,
    section: SURFACE_SECTION_KEYS.BLOCK,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_BLOCK,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR,
  },
  EDITOR_LINE_STYLE: {
    key: "editorLineStyle",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.LEAF,
    section: SURFACE_SECTION_KEYS.LINE,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_LINE,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR,
  },
  EDITOR_SELECTION_STYLE: {
    key: "editorSelectionStyle",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.LEAF,
    section: SURFACE_SECTION_KEYS.SELECTION,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_SELECTION,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR,
  },
  EDITOR_GLYPH_COLOR: {
    key: "editorGlyphColor",
    surface: SURFACE_KEYS.EDITOR,
    scope: SURFACE_ACTION_SCOPES.LEAF,
    section: SURFACE_SECTION_KEYS.GLYPH,
    renderTarget: SURFACE_RENDER_TARGETS.EDITOR_GLYPH,
    persistTarget: SURFACE_PERSIST_TARGETS.EDITOR_GLYPHS,
  },
});
