// Generated from editor.js preset data.

export const themeColorPresets = [
  {
    key: "defaultGold",
    label: "Gold",
    vars: {
      "--accent": "#f4c76a",
      "--accent-2": "#ffb15c",
      "--accent-3": "#f4c76a",
      "--brand-color": "rgba(244, 199, 106, 0.96)",
      "--brand-glow": "rgba(244, 199, 106, 0.08)",
    },
  },
  {
    key: "violet",
    label: "Violet",
    vars: {
      "--accent": "#8b5cf6",
      "--accent-2": "#a78bfa",
      "--accent-3": "#c4b5fd",
      "--brand-color": "rgba(196, 181, 253, 0.96)",
      "--brand-glow": "rgba(196, 181, 253, 0.08)",
    },
  },
  {
    key: "ice",
    label: "Ice Blue",
    vars: {
      "--accent": "#60a5fa",
      "--accent-2": "#7dd3fc",
      "--accent-3": "#93c5fd",
      "--brand-color": "rgba(147, 197, 253, 0.96)",
      "--brand-glow": "rgba(147, 197, 253, 0.08)",
    },
  },
  {
    key: "emerald",
    label: "Emerald",
    vars: {
      "--accent": "#34D399",
      "--accent-2": "#6EE7B7",
      "--accent-3": "#A7F3D0",
      "--brand-color": "rgba(110, 231, 183, 0.96)",
      "--brand-glow": "rgba(110, 231, 183, 0.08)",
    },
  },
  {
    key: "quartz",
    label: "Quartz",
    vars: {
      "--accent": "#E5E7EB",
      "--accent-2": "#F3F4F6",
      "--accent-3": "#D1D5DB",
      "--brand-color": "rgba(243, 244, 246, 0.96)",
      "--brand-glow": "rgba(243, 244, 246, 0.08)",
    },
  },
  {
    key: "rose",
    label: "Rose",
    vars: {
      "--accent": "#F472B6",
      "--accent-2": "#F9A8D4",
      "--accent-3": "#FBCFE8",
      "--brand-color": "rgba(249, 168, 212, 0.96)",
      "--brand-glow": "rgba(249, 168, 212, 0.08)",
    },
  },
];
export const themeBackgroundPresets = [
  {
    key: "graphite",
    label: "Graphite",
    mode: "dark",
    vars: {
      "--bg": "#0f1115",
      "--bg-2": "#171a21",
      "--panel": "rgba(19, 21, 26, 0.84)",
      "--panel-2": "rgba(255, 255, 255, 0.025)",
      "--shell-bg": "rgba(10, 12, 16, 0.46)",
      "--line": "rgba(255, 255, 255, 0.07)",
      "--line-strong": "rgba(255, 255, 255, 0.12)",
      "--text": "#edf1f4",
      "--muted": "#98a0aa",
    },
  },
  {
    key: "midnight",
    label: "Midnight",
    mode: "dark",
    vars: {
      "--bg": "#0b0f16",
      "--bg-2": "#121822",
      "--panel": "rgba(13, 17, 24, 0.88)",
      "--panel-2": "rgba(255, 255, 255, 0.02)",
      "--shell-bg": "rgba(8, 11, 18, 0.52)",
      "--line": "rgba(255, 255, 255, 0.065)",
      "--line-strong": "rgba(255, 255, 255, 0.11)",
      "--text": "#edf1f4",
      "--muted": "#92a0b3",
    },
  },
  {
    key: "carbon",
    label: "Carbon",
    mode: "dark",
    vars: {
      "--bg": "#131313",
      "--bg-2": "#1a1a1a",
      "--panel": "rgba(22, 22, 22, 0.86)",
      "--panel-2": "rgba(255, 255, 255, 0.022)",
      "--shell-bg": "rgba(14, 14, 14, 0.52)",
      "--line": "rgba(255, 255, 255, 0.065)",
      "--line-strong": "rgba(255, 255, 255, 0.105)",
      "--text": "#f2f2f2",
      "--muted": "#a0a0a0",
    },
  },
  {
    key: "fog",
    label: "Fog",
    mode: "dark",
    vars: {
      "--bg": "#101317",
      "--bg-2": "#181d23",
      "--panel": "rgba(21, 25, 31, 0.82)",
      "--panel-2": "rgba(255, 255, 255, 0.03)",
      "--shell-bg": "rgba(13, 16, 21, 0.48)",
      "--line": "rgba(255, 255, 255, 0.075)",
      "--line-strong": "rgba(255, 255, 255, 0.125)",
      "--text": "#edf1f4",
      "--muted": "#9aa5b1",
    },
  },
  {
    key: "obsidian",
    label: "Obsidian",
    mode: "dark",
    vars: {
      "--bg": "#090B0F",
      "--bg-2": "#11151B",
      "--panel": "rgba(13, 16, 21, 0.9)",
      "--panel-2": "rgba(255, 255, 255, 0.018)",
      "--shell-bg": "rgba(7, 9, 13, 0.6)",
      "--line": "rgba(255, 255, 255, 0.055)",
      "--line-strong": "rgba(255, 255, 255, 0.095)",
      "--text": "#F3F4F6",
      "--muted": "#9CA3AF",
    },
  },
  {
    key: "blueprint",
    label: "Blueprint",
    mode: "dark",
    vars: {
      "--bg": "#0D1320",
      "--bg-2": "#151D2C",
      "--panel": "rgba(16, 22, 34, 0.88)",
      "--panel-2": "rgba(147, 197, 253, 0.025)",
      "--shell-bg": "rgba(10, 16, 28, 0.56)",
      "--line": "rgba(148, 163, 184, 0.08)",
      "--line-strong": "rgba(148, 163, 184, 0.13)",
      "--text": "#E5EDF8",
      "--muted": "#8FA2BC",
    },
  },
  {
    key: "paper",
    label: "Paper",
    mode: "light",
    vars: {
      "--bg": "#F5F6F8",
      "--bg-2": "#ECEEF2",
      "--panel": "rgba(255, 255, 255, 0.9)",
      "--panel-2": "rgba(17, 17, 17, 0.022)",
      "--shell-bg": "rgba(255, 255, 255, 0.82)",
      "--line": "rgba(17, 17, 17, 0.12)",
      "--line-strong": "rgba(17, 17, 17, 0.2)",
      "--text": "#111111",
      "--muted": "#4F5560",
    },
  },
  {
    key: "porcelain",
    label: "Porcelain",
    mode: "light",
    vars: {
      "--bg": "#F4F7FB",
      "--bg-2": "#EAF0F7",
      "--panel": "rgba(255, 255, 255, 0.88)",
      "--panel-2": "rgba(17, 17, 17, 0.02)",
      "--shell-bg": "rgba(255, 255, 255, 0.78)",
      "--line": "rgba(17, 17, 17, 0.12)",
      "--line-strong": "rgba(17, 17, 17, 0.19)",
      "--text": "#111111",
      "--muted": "#556274",
    },
  },
  {
    key: "linen",
    label: "Linen",
    mode: "light",
    vars: {
      "--bg": "#FAF7F2",
      "--bg-2": "#F2EDE4",
      "--panel": "rgba(255, 255, 255, 0.84)",
      "--panel-2": "rgba(17, 17, 17, 0.02)",
      "--shell-bg": "rgba(255, 255, 255, 0.74)",
      "--line": "rgba(17, 17, 17, 0.12)",
      "--line-strong": "rgba(17, 17, 17, 0.19)",
      "--text": "#111111",
      "--muted": "#61584C",
    },
  },
];
export const themeTextPresets = [
  { key: "mist", label: "Mist", mode: "dark", vars: { "--text": "#EDF1F4" } },
  { key: "bright", label: "Bright", mode: "dark", vars: { "--text": "#F8FAFC" } },
  { key: "cool", label: "Cool", mode: "dark", vars: { "--text": "#E2E8F0" } },
  { key: "ink", label: "Ink", mode: "light", vars: { "--text": "#111111" } },
  { key: "graphiteText", label: "Graphite", mode: "light", vars: { "--text": "#1A1A1A" } },
];
export const themeLinePresets = [
  {
    key: "soft",
    label: "Soft",
    mode: "dark",
    vars: {
      "--line": "rgba(255, 255, 255, 0.07)",
      "--line-strong": "rgba(255, 255, 255, 0.12)",
    },
  },
  {
    key: "crisp",
    label: "Crisp",
    mode: "dark",
    vars: {
      "--line": "rgba(255, 255, 255, 0.1)",
      "--line-strong": "rgba(255, 255, 255, 0.16)",
    },
  },
  {
    key: "coolLines",
    label: "Cool",
    mode: "dark",
    vars: {
      "--line": "rgba(148, 163, 184, 0.12)",
      "--line-strong": "rgba(148, 163, 184, 0.18)",
    },
  },
  {
    key: "paperLines",
    label: "Paper",
    mode: "light",
    vars: {
      "--line": "rgba(17, 17, 17, 0.12)",
      "--line-strong": "rgba(17, 17, 17, 0.2)",
    },
  },
];
export const themePalettePresets = [
  {
    key: "graphiteGold",
    label: "Default",
    mode: "dark",
    themeColorKey: "defaultGold",
    themeTextKey: "mist",
    themeBackgroundKey: "graphite",
    themeLineKey: "soft",
  },
  {
    key: "blueprintIce",
    label: "Blueprint Ice",
    mode: "dark",
    themeColorKey: "ice",
    themeTextKey: "cool",
    themeBackgroundKey: "blueprint",
    themeLineKey: "coolLines",
  },
  {
    key: "obsidianQuartz",
    label: "Obsidian Quartz",
    mode: "dark",
    themeColorKey: "quartz",
    themeTextKey: "bright",
    themeBackgroundKey: "obsidian",
    themeLineKey: "crisp",
  },
  {
    key: "violetSignal",
    label: "Violet Signal",
    mode: "dark",
    themeColorKey: "violet",
    themeTextKey: "mist",
    themeBackgroundKey: "fog",
    themeLineKey: "soft",
  },
  {
    key: "paperGold",
    label: "Default",
    mode: "light",
    themeColorKey: "defaultGold",
    themeTextKey: "ink",
    themeBackgroundKey: "paper",
    themeLineKey: "paperLines",
  },
  {
    key: "porcelainIce",
    label: "Porcelain Ice",
    mode: "light",
    themeColorKey: "ice",
    themeTextKey: "ink",
    themeBackgroundKey: "porcelain",
    themeLineKey: "paperLines",
  },
  {
    key: "linenRose",
    label: "Linen Rose",
    mode: "light",
    themeColorKey: "rose",
    themeTextKey: "ink",
    themeBackgroundKey: "linen",
    themeLineKey: "paperLines",
  },
];
export const interfaceFontOptionsList = [
  { key: "defaultSans", label: "Default Sans", value: '"IBM Plex Sans", "Inter", "Noto Sans", sans-serif' },
  { key: "inter", label: "Inter", value: '"Inter", "IBM Plex Sans", "Noto Sans", sans-serif' },
  { key: "plexSans", label: "IBM Plex Sans", value: '"IBM Plex Sans", "Inter", "Noto Sans", sans-serif' },
  { key: "recursiveSans", label: "Recursive Sans", value: '"Recursive", "Inter", "IBM Plex Sans", sans-serif' },
  { key: "spaceGrotesk", label: "Space Grotesk", value: '"Space Grotesk", "Inter", "IBM Plex Sans", sans-serif' },
  { key: "plusJakartaSans", label: "Plus Jakarta Sans", value: '"Plus Jakarta Sans", "Inter", "IBM Plex Sans", sans-serif' },
  { key: "sora", label: "Sora", value: '"Sora", "Inter", "IBM Plex Sans", sans-serif' },
  { key: "sourceSans3", label: "Source Sans 3", value: '"Source Sans 3", "Inter", "IBM Plex Sans", sans-serif' },
  { key: "monaSans", label: "Mona Sans", value: '"Mona Sans", "Inter", "IBM Plex Sans", sans-serif' },
];
export const interfaceSizeOptionsList = [
  {
    key: "13",
    size: 13,
    label: "13",
    vars: {
      "--ui-font-size": "13px",
      "--sidebar-title-size": "13px",
      "--setting-copy-size": "11px",
      "--pill-font-size": "10px",
      "--setting-subtitle-size": "12px",
      "--tab-label-size": "12px",
      "--tree-name-size": "12px",
      "--workspace-path-size": "12px",
      "--action-font-size": "12px",
    },
  },
  {
    key: "14",
    size: 14,
    label: "14",
    vars: {
      "--ui-font-size": "14px",
      "--sidebar-title-size": "14px",
      "--setting-copy-size": "12px",
      "--pill-font-size": "10px",
      "--setting-subtitle-size": "12px",
      "--tab-label-size": "12px",
      "--tree-name-size": "12px",
      "--workspace-path-size": "12px",
      "--action-font-size": "13px",
    },
  },
  {
    key: "15",
    size: 15,
    label: "15",
    vars: {
      "--ui-font-size": "15px",
      "--sidebar-title-size": "15px",
      "--setting-copy-size": "13px",
      "--pill-font-size": "11px",
      "--setting-subtitle-size": "13px",
      "--tab-label-size": "13px",
      "--tree-name-size": "13px",
      "--workspace-path-size": "13px",
      "--action-font-size": "14px",
    },
  },
  {
    key: "16",
    size: 16,
    label: "16",
    vars: {
      "--ui-font-size": "16px",
      "--sidebar-title-size": "16px",
      "--setting-copy-size": "14px",
      "--pill-font-size": "12px",
      "--setting-subtitle-size": "14px",
      "--tab-label-size": "14px",
      "--tree-name-size": "14px",
      "--workspace-path-size": "14px",
      "--action-font-size": "15px",
    },
  },
  {
    key: "17",
    size: 17,
    label: "17",
    vars: {
      "--ui-font-size": "17px",
      "--sidebar-title-size": "17px",
      "--setting-copy-size": "15px",
      "--pill-font-size": "13px",
      "--setting-subtitle-size": "15px",
      "--tab-label-size": "15px",
      "--tree-name-size": "15px",
      "--workspace-path-size": "15px",
      "--action-font-size": "16px",
    },
  },
];
export const editorFontOptionsList = [
  { key: "jetbrainsMono", label: "JetBrains Mono", value: '"JetBrains Mono", "IBM Plex Mono", "Recursive", monospace' },
  { key: "ibmPlexMono", label: "IBM Plex Mono", value: '"IBM Plex Mono", "JetBrains Mono", "Recursive", monospace' },
  { key: "recursive", label: "Recursive", value: '"Recursive", "JetBrains Mono", "IBM Plex Mono", monospace' },
  { key: "monaspace", label: "Monaspace Neon", value: '"Monaspace Neon", "JetBrains Mono", "Source Code Pro", monospace' },
  { key: "sourceCodePro", label: "Source Code Pro", value: '"Source Code Pro", "JetBrains Mono", "IBM Plex Mono", monospace' },
];
export const editorFontSizePresets = [
  { key: "13", size: 13, label: "13", vars: { "--editor-font-size": "13px", "--editor-line-height": "23px" } },
  { key: "14", size: 14, label: "14", vars: { "--editor-font-size": "14px", "--editor-line-height": "24px" } },
  { key: "15", size: 15, label: "15", vars: { "--editor-font-size": "15px", "--editor-line-height": "26px" } },
  { key: "16", size: 16, label: "16", vars: { "--editor-font-size": "16px", "--editor-line-height": "28px" } },
  { key: "17", size: 17, label: "17", vars: { "--editor-font-size": "17px", "--editor-line-height": "30px" } },
];
export const legacyInterfaceSizeKeyMap = {
  "1": "13",
  compact: "14",
  default: "15",
  comfortable: "16",
  large: "17",
};
export const legacyThemeColorKeyMap = {
  styioGold: "defaultGold",
  "Styio Gold": "Gold",
  "Default Gold": "Gold",
};
export const legacyInterfaceFontKeyMap = {
  styioSans: "defaultSans",
  "Styio Sans": "Default Sans",
};
export const legacyEditorFontSizeKeyMap = {
  "1": "13",
  compact: "14",
  default: "15",
  large: "16",
  "5": "17",
};
export const legacyEditorTextHighlightKeyMap = {
  styioGold: "defaultGold",
  "Styio Gold": "Gold",
  "Default Gold": "Gold",
};
export const legacyDefaultGlyphPaletteKeyMap = {
  styio: "default",
  Styio: "Default",
};
export const editorBackgroundPresets = [
  {
    key: "graphite",
    label: "Graphite",
    mode: "dark",
    vars: {
      "--editor": "#15171C",
      "--editor-gutter-bg": "#1C1F26",
      "--editor-frame-border": "rgba(232, 236, 241, 0.08)",
      "--editor-surface-overlay-top": "rgba(255, 255, 255, 0.03)",
      "--editor-surface-overlay-bottom": "rgba(255, 255, 255, 0.012)",
    },
  },
  {
    key: "midnight",
    label: "Midnight",
    mode: "dark",
    vars: {
      "--editor": "#10141D",
      "--editor-gutter-bg": "#171C26",
      "--editor-frame-border": "rgba(232, 236, 241, 0.075)",
      "--editor-surface-overlay-top": "rgba(255, 255, 255, 0.02)",
      "--editor-surface-overlay-bottom": "rgba(255, 255, 255, 0.008)",
    },
  },
  {
    key: "carbon",
    label: "Carbon",
    mode: "dark",
    vars: {
      "--editor": "#171717",
      "--editor-gutter-bg": "#1F1F1F",
      "--editor-frame-border": "rgba(242, 242, 242, 0.08)",
      "--editor-surface-overlay-top": "rgba(255, 255, 255, 0.018)",
      "--editor-surface-overlay-bottom": "rgba(255, 255, 255, 0.006)",
    },
  },
  {
    key: "slate",
    label: "Slate",
    mode: "dark",
    vars: {
      "--editor": "#1A2029",
      "--editor-gutter-bg": "#202733",
      "--editor-frame-border": "rgba(237, 241, 244, 0.08)",
      "--editor-surface-overlay-top": "rgba(255, 255, 255, 0.026)",
      "--editor-surface-overlay-bottom": "rgba(255, 255, 255, 0.01)",
    },
  },
  {
    key: "paper",
    label: "Paper",
    mode: "light",
    vars: {
      "--editor": "#FBFBFC",
      "--editor-gutter-bg": "#F2F4F7",
      "--editor-frame-border": "rgba(17, 17, 17, 0.1)",
      "--editor-surface-overlay-top": "rgba(17, 17, 17, 0.01)",
      "--editor-surface-overlay-bottom": "rgba(17, 17, 17, 0.004)",
    },
  },
  {
    key: "sky",
    label: "Sky",
    mode: "light",
    vars: {
      "--editor": "#F7FAFE",
      "--editor-gutter-bg": "#EEF4FB",
      "--editor-frame-border": "rgba(17, 17, 17, 0.1)",
      "--editor-surface-overlay-top": "rgba(96, 165, 250, 0.01)",
      "--editor-surface-overlay-bottom": "rgba(96, 165, 250, 0.005)",
    },
  },
  {
    key: "mint",
    label: "Mint",
    mode: "light",
    vars: {
      "--editor": "#F6FBF8",
      "--editor-gutter-bg": "#ECF6F2",
      "--editor-frame-border": "rgba(17, 17, 17, 0.1)",
      "--editor-surface-overlay-top": "rgba(52, 211, 153, 0.01)",
      "--editor-surface-overlay-bottom": "rgba(52, 211, 153, 0.005)",
    },
  },
];
export const editorTextColorPresets = [
  {
    key: "mist",
    label: "Mist",
    mode: "dark",
    vars: {
      "--editor-text": "#E8ECF1",
      "--editor-muted": "#7F8893",
    },
  },
  {
    key: "bright",
    label: "Bright",
    mode: "dark",
    vars: {
      "--editor-text": "#F6F8FB",
      "--editor-muted": "#9CA7B3",
    },
  },
  {
    key: "soft",
    label: "Soft",
    mode: "dark",
    vars: {
      "--editor-text": "#D7DEE6",
      "--editor-muted": "#7D8894",
    },
  },
  {
    key: "warm",
    label: "Warm",
    mode: "dark",
    vars: {
      "--editor-text": "#F1E9DC",
      "--editor-muted": "#A89883",
    },
  },
  {
    key: "ink",
    label: "Ink",
    mode: "light",
    vars: {
      "--editor-text": "#111111",
      "--editor-muted": "#5F6772",
    },
  },
  {
    key: "graphiteText",
    label: "Graphite",
    mode: "light",
    vars: {
      "--editor-text": "#1A1A1A",
      "--editor-muted": "#5F6772",
    },
  },
];
export const editorTextHighlightPresets = [
  { key: "defaultGold", label: "Gold", color: "#F4C76A", caretShadow: "rgba(244, 199, 106, 0.18)" },
  { key: "violet", label: "Violet", color: "#8B5CF6", caretShadow: "rgba(139, 92, 246, 0.18)" },
  { key: "ice", label: "Ice Blue", color: "#60A5FA", caretShadow: "rgba(96, 165, 250, 0.18)" },
  { key: "emerald", label: "Emerald", color: "#34D399", caretShadow: "rgba(52, 211, 153, 0.18)" },
  { key: "quartz", label: "Quartz", color: "#E5E7EB", caretShadow: "rgba(229, 231, 235, 0.16)" },
];
